<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="1" hostname="Тоха" failures="4" tests="5" name="First test suite" time="0.081" errors="0" timestamp="29 нояб. 2018 08:14:32 GMT">
  <testcase classname="triangle_test.Test_getSquareOfTriangle" name="test_SquareOverflow" time="0.016">
    <failure type="org.testng.TestException" message="
Method Test_getSquareOfTriangle.test_SquareOverflow()[pri:0, instance:triangle_test.Test_getSquareOfTriangle@1190200a] should have thrown an exception of type class java.lang.Exception">
      <![CDATA[org.testng.TestException: 
Method Test_getSquareOfTriangle.test_SquareOverflow()[pri:0, instance:triangle_test.Test_getSquareOfTriangle@1190200a] should have thrown an exception of type class java.lang.Exception
... Removed 22 stack frames]]>
    </failure>
  </testcase> <!-- test_SquareOverflow -->
  <testcase classname="triangle_test.Test_getSquareOfTriangle" name="test_getSquareNegManual" time="0.002">
    <failure type="java.lang.AssertionError" message="Calculates square of triangle with negative side">
      <![CDATA[java.lang.AssertionError: Calculates square of triangle with negative side
	at triangle_test.Test_getSquareOfTriangle.test_getSquareNegManual(Test_getSquareOfTriangle.java:60)
... Removed 26 stack frames]]>
    </failure>
  </testcase> <!-- test_getSquareNegManual -->
  <testcase classname="triangle_test.Test_getSquareOfTriangle" name="test_getSquareNegativeSide" time="0.005">
    <failure type="java.lang.AssertionError" message="expected [6] but found [6.0]">
      <![CDATA[java.lang.AssertionError: expected [6] but found [6.0]
	at triangle_test.Test_getSquareOfTriangle.test_getSquareNegativeSide(Test_getSquareOfTriangle.java:52)
... Removed 30 stack frames]]>
    </failure>
  </testcase> <!-- test_getSquareNegativeSide -->
  <testcase classname="triangle_test.Test_getSquareOfTriangle" name="test_getSquareRectangTrianAnotherEquation" time="0.003"/>
  <testcase classname="triangle_test.Test_getSquareOfTriangle" name="test_getSquareTrCantExist" time="0.002">
    <failure type="java.lang.AssertionError" message="expected [3] but found [NaN]">
      <![CDATA[java.lang.AssertionError: expected [3] but found [NaN]
	at triangle_test.Test_getSquareOfTriangle.test_getSquareTrCantExist(Test_getSquareOfTriangle.java:36)
... Removed 30 stack frames]]>
    </failure>
  </testcase> <!-- test_getSquareTrCantExist -->
  <testcase classname="triangle_test.Test_getSquareOfTriangle" name="test_getSquare" time="0.0">
    <ignored/>
  </testcase> <!-- test_getSquare -->
</testsuite> <!-- First test suite -->
